[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = test_*.py *_tests.py api_tests.py
addopts = --reuse-db --nomigrations --cov=people --cov=utils --cov-report=term-missing
testpaths =
    people
    utils
