# Generated by Django 5.2.12 on 2026-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_patientcompanioncheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('max_capacity', models.PositiveIntegerField(default=20, help_text='Número máximo de pessoas que podem estar hospedadas simultaneamente', verbose_name='Capacidade Máxima de Vagas')),
            ],
            options={
                'verbose_name': 'Configuração da Casa',
                'verbose_name_plural': 'Configurações da Casa',
            },
        ),
    ]
