# Generated by Django 5.2.12 on 2026-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_houseconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão')], max_length=12)),
                ('entity', models.CharField(max_length=80)),
                ('object_id', models.PositiveIntegerField()),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity', 'object_id'], name='people_audi_entity_5dc165_idx'), models.Index(fields=['created_at'], name='people_audi_created_8adb80_idx')],
            },
        ),
    ]
